/*
 * generated by Xtext 2.19.0
 */
package fr.cea.nabla.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractNablaScopeProvider extends DelegatingScopeProvider {
}
