/*
 * generated by Xtext 2.17.0
 */
package fr.inria.diverse.ide

import com.google.inject.Guice
import fr.inria.diverse.KauluaRuntimeModule
import fr.inria.diverse.KauluaStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class KauluaIdeSetup extends KauluaStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new KauluaRuntimeModule, new KauluaIdeModule))
	}
	
}
