/**
 * generated by Xtext 2.19.0
 */
package fr.cea.nabla.nabla.impl;

import fr.cea.nabla.nabla.NablaPackage;
import fr.cea.nabla.nabla.ScalarVar;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Scalar Var</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ScalarVarImpl extends VarImpl implements ScalarVar
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ScalarVarImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NablaPackage.Literals.SCALAR_VAR;
  }

} //ScalarVarImpl
