/*
 * generated by Xtext 2.19.0
 */
package fr.inria.diverse.parser.antlr;

import com.google.inject.Inject;
import fr.inria.diverse.parser.antlr.internal.InternalKauluaParser;
import fr.inria.diverse.services.KauluaGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class KauluaParser extends AbstractAntlrParser {

	@Inject
	private KauluaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalKauluaParser createParser(XtextTokenStream stream) {
		return new InternalKauluaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Protocol";
	}

	public KauluaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KauluaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
