/**
 * generated by Xtext 2.19.0
 */
package fr.inria.diverse.kaulua;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.kaulua.Feature#isIsMandatory <em>Is Mandatory</em>}</li>
 *   <li>{@link fr.inria.diverse.kaulua.Feature#getName <em>Name</em>}</li>
 *   <li>{@link fr.inria.diverse.kaulua.Feature#getCapabilities <em>Capabilities</em>}</li>
 *   <li>{@link fr.inria.diverse.kaulua.Feature#getAlternativeGroup <em>Alternative Group</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.kaulua.KauluaPackage#getFeature()
 * @model
 * @generated
 */
public interface Feature extends EObject
{
  /**
   * Returns the value of the '<em><b>Is Mandatory</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Mandatory</em>' attribute.
   * @see #setIsMandatory(boolean)
   * @see fr.inria.diverse.kaulua.KauluaPackage#getFeature_IsMandatory()
   * @model
   * @generated
   */
  boolean isIsMandatory();

  /**
   * Sets the value of the '{@link fr.inria.diverse.kaulua.Feature#isIsMandatory <em>Is Mandatory</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Mandatory</em>' attribute.
   * @see #isIsMandatory()
   * @generated
   */
  void setIsMandatory(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.inria.diverse.kaulua.KauluaPackage#getFeature_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.inria.diverse.kaulua.Feature#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Capabilities</b></em>' containment reference list.
   * The list contents are of type {@link fr.inria.diverse.kaulua.Capability}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Capabilities</em>' containment reference list.
   * @see fr.inria.diverse.kaulua.KauluaPackage#getFeature_Capabilities()
   * @model containment="true"
   * @generated
   */
  EList<Capability> getCapabilities();

  /**
   * Returns the value of the '<em><b>Alternative Group</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alternative Group</em>' attribute.
   * @see #setAlternativeGroup(String)
   * @see fr.inria.diverse.kaulua.KauluaPackage#getFeature_AlternativeGroup()
   * @model
   * @generated
   */
  String getAlternativeGroup();

  /**
   * Sets the value of the '{@link fr.inria.diverse.kaulua.Feature#getAlternativeGroup <em>Alternative Group</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alternative Group</em>' attribute.
   * @see #getAlternativeGroup()
   * @generated
   */
  void setAlternativeGroup(String value);

} // Feature
