/**
 * generated by Xtext 2.19.0
 */
package fr.inria.diverse.kaulua.impl;

import fr.inria.diverse.kaulua.Capability;
import fr.inria.diverse.kaulua.KauluaPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Capability</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.kaulua.impl.CapabilityImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.inria.diverse.kaulua.impl.CapabilityImpl#getDefinitionFile <em>Definition File</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CapabilityImpl extends MinimalEObjectImpl.Container implements Capability
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getDefinitionFile() <em>Definition File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefinitionFile()
   * @generated
   * @ordered
   */
  protected static final String DEFINITION_FILE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDefinitionFile() <em>Definition File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefinitionFile()
   * @generated
   * @ordered
   */
  protected String definitionFile = DEFINITION_FILE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CapabilityImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return KauluaPackage.Literals.CAPABILITY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KauluaPackage.CAPABILITY__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDefinitionFile()
  {
    return definitionFile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDefinitionFile(String newDefinitionFile)
  {
    String oldDefinitionFile = definitionFile;
    definitionFile = newDefinitionFile;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KauluaPackage.CAPABILITY__DEFINITION_FILE, oldDefinitionFile, definitionFile));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case KauluaPackage.CAPABILITY__NAME:
        return getName();
      case KauluaPackage.CAPABILITY__DEFINITION_FILE:
        return getDefinitionFile();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case KauluaPackage.CAPABILITY__NAME:
        setName((String)newValue);
        return;
      case KauluaPackage.CAPABILITY__DEFINITION_FILE:
        setDefinitionFile((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case KauluaPackage.CAPABILITY__NAME:
        setName(NAME_EDEFAULT);
        return;
      case KauluaPackage.CAPABILITY__DEFINITION_FILE:
        setDefinitionFile(DEFINITION_FILE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case KauluaPackage.CAPABILITY__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case KauluaPackage.CAPABILITY__DEFINITION_FILE:
        return DEFINITION_FILE_EDEFAULT == null ? definitionFile != null : !DEFINITION_FILE_EDEFAULT.equals(definitionFile);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", definitionFile: ");
    result.append(definitionFile);
    result.append(')');
    return result.toString();
  }

} //CapabilityImpl
