/**
 * generated by Xtext 2.19.0
 */
package fr.inria.diverse.kaulua.impl;

import fr.inria.diverse.kaulua.Capability;
import fr.inria.diverse.kaulua.Feature;
import fr.inria.diverse.kaulua.KauluaPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Feature</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.kaulua.impl.FeatureImpl#isIsMandatory <em>Is Mandatory</em>}</li>
 *   <li>{@link fr.inria.diverse.kaulua.impl.FeatureImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.inria.diverse.kaulua.impl.FeatureImpl#getCapabilities <em>Capabilities</em>}</li>
 *   <li>{@link fr.inria.diverse.kaulua.impl.FeatureImpl#getAlternativeGroup <em>Alternative Group</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FeatureImpl extends MinimalEObjectImpl.Container implements Feature
{
  /**
   * The default value of the '{@link #isIsMandatory() <em>Is Mandatory</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsMandatory()
   * @generated
   * @ordered
   */
  protected static final boolean IS_MANDATORY_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsMandatory() <em>Is Mandatory</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsMandatory()
   * @generated
   * @ordered
   */
  protected boolean isMandatory = IS_MANDATORY_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getCapabilities() <em>Capabilities</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCapabilities()
   * @generated
   * @ordered
   */
  protected EList<Capability> capabilities;

  /**
   * The default value of the '{@link #getAlternativeGroup() <em>Alternative Group</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlternativeGroup()
   * @generated
   * @ordered
   */
  protected static final String ALTERNATIVE_GROUP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAlternativeGroup() <em>Alternative Group</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlternativeGroup()
   * @generated
   * @ordered
   */
  protected String alternativeGroup = ALTERNATIVE_GROUP_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FeatureImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return KauluaPackage.Literals.FEATURE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsMandatory()
  {
    return isMandatory;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsMandatory(boolean newIsMandatory)
  {
    boolean oldIsMandatory = isMandatory;
    isMandatory = newIsMandatory;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KauluaPackage.FEATURE__IS_MANDATORY, oldIsMandatory, isMandatory));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KauluaPackage.FEATURE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Capability> getCapabilities()
  {
    if (capabilities == null)
    {
      capabilities = new EObjectContainmentEList<Capability>(Capability.class, this, KauluaPackage.FEATURE__CAPABILITIES);
    }
    return capabilities;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAlternativeGroup()
  {
    return alternativeGroup;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAlternativeGroup(String newAlternativeGroup)
  {
    String oldAlternativeGroup = alternativeGroup;
    alternativeGroup = newAlternativeGroup;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KauluaPackage.FEATURE__ALTERNATIVE_GROUP, oldAlternativeGroup, alternativeGroup));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case KauluaPackage.FEATURE__CAPABILITIES:
        return ((InternalEList<?>)getCapabilities()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case KauluaPackage.FEATURE__IS_MANDATORY:
        return isIsMandatory();
      case KauluaPackage.FEATURE__NAME:
        return getName();
      case KauluaPackage.FEATURE__CAPABILITIES:
        return getCapabilities();
      case KauluaPackage.FEATURE__ALTERNATIVE_GROUP:
        return getAlternativeGroup();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case KauluaPackage.FEATURE__IS_MANDATORY:
        setIsMandatory((Boolean)newValue);
        return;
      case KauluaPackage.FEATURE__NAME:
        setName((String)newValue);
        return;
      case KauluaPackage.FEATURE__CAPABILITIES:
        getCapabilities().clear();
        getCapabilities().addAll((Collection<? extends Capability>)newValue);
        return;
      case KauluaPackage.FEATURE__ALTERNATIVE_GROUP:
        setAlternativeGroup((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case KauluaPackage.FEATURE__IS_MANDATORY:
        setIsMandatory(IS_MANDATORY_EDEFAULT);
        return;
      case KauluaPackage.FEATURE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case KauluaPackage.FEATURE__CAPABILITIES:
        getCapabilities().clear();
        return;
      case KauluaPackage.FEATURE__ALTERNATIVE_GROUP:
        setAlternativeGroup(ALTERNATIVE_GROUP_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case KauluaPackage.FEATURE__IS_MANDATORY:
        return isMandatory != IS_MANDATORY_EDEFAULT;
      case KauluaPackage.FEATURE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case KauluaPackage.FEATURE__CAPABILITIES:
        return capabilities != null && !capabilities.isEmpty();
      case KauluaPackage.FEATURE__ALTERNATIVE_GROUP:
        return ALTERNATIVE_GROUP_EDEFAULT == null ? alternativeGroup != null : !ALTERNATIVE_GROUP_EDEFAULT.equals(alternativeGroup);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (isMandatory: ");
    result.append(isMandatory);
    result.append(", name: ");
    result.append(name);
    result.append(", alternativeGroup: ");
    result.append(alternativeGroup);
    result.append(')');
    return result.toString();
  }

} //FeatureImpl
