/**
 * generated by Xtext 2.19.0
 */
package fr.cea.nabla.nabla;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Connectivity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.cea.nabla.nabla.Connectivity#getName <em>Name</em>}</li>
 *   <li>{@link fr.cea.nabla.nabla.Connectivity#getInTypes <em>In Types</em>}</li>
 *   <li>{@link fr.cea.nabla.nabla.Connectivity#getReturnType <em>Return Type</em>}</li>
 * </ul>
 *
 * @see fr.cea.nabla.nabla.NablaPackage#getConnectivity()
 * @model
 * @generated
 */
public interface Connectivity extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.cea.nabla.nabla.NablaPackage#getConnectivity_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.cea.nabla.nabla.Connectivity#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>In Types</b></em>' attribute list.
   * The list contents are of type {@link fr.cea.nabla.nabla.ItemType}.
   * The literals are from the enumeration {@link fr.cea.nabla.nabla.ItemType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>In Types</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>In Types</em>' attribute list.
   * @see fr.cea.nabla.nabla.ItemType
   * @see fr.cea.nabla.nabla.NablaPackage#getConnectivity_InTypes()
   * @model unique="false"
   * @generated
   */
  EList<ItemType> getInTypes();

  /**
   * Returns the value of the '<em><b>Return Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Return Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Return Type</em>' containment reference.
   * @see #setReturnType(ItemArgType)
   * @see fr.cea.nabla.nabla.NablaPackage#getConnectivity_ReturnType()
   * @model containment="true"
   * @generated
   */
  ItemArgType getReturnType();

  /**
   * Sets the value of the '{@link fr.cea.nabla.nabla.Connectivity#getReturnType <em>Return Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Return Type</em>' containment reference.
   * @see #getReturnType()
   * @generated
   */
  void setReturnType(ItemArgType value);

} // Connectivity
