/**
 * generated by Xtext 2.19.0
 */
package fr.cea.nabla.nabla;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaration Block</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.cea.nabla.nabla.NablaPackage#getDeclarationBlock()
 * @model
 * @generated
 */
public interface DeclarationBlock extends EObject
{
} // DeclarationBlock
