/**
 * generated by Xtext 2.19.0
 */
package fr.cea.nabla.nabla;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.cea.nabla.nabla.Function#getArgGroups <em>Arg Groups</em>}</li>
 * </ul>
 *
 * @see fr.cea.nabla.nabla.NablaPackage#getFunction()
 * @model
 * @generated
 */
public interface Function extends Callable
{
  /**
   * Returns the value of the '<em><b>Arg Groups</b></em>' containment reference list.
   * The list contents are of type {@link fr.cea.nabla.nabla.FunctionArg}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arg Groups</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg Groups</em>' containment reference list.
   * @see fr.cea.nabla.nabla.NablaPackage#getFunction_ArgGroups()
   * @model containment="true"
   * @generated
   */
  EList<FunctionArg> getArgGroups();

} // Function
