/**
 * generated by Xtext 2.19.0
 */
package fr.cea.nabla.nabla;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Module</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.cea.nabla.nabla.NablaModule#getName <em>Name</em>}</li>
 *   <li>{@link fr.cea.nabla.nabla.NablaModule#getImports <em>Imports</em>}</li>
 *   <li>{@link fr.cea.nabla.nabla.NablaModule#getBlocks <em>Blocks</em>}</li>
 *   <li>{@link fr.cea.nabla.nabla.NablaModule#getVariables <em>Variables</em>}</li>
 *   <li>{@link fr.cea.nabla.nabla.NablaModule#getJobs <em>Jobs</em>}</li>
 * </ul>
 *
 * @see fr.cea.nabla.nabla.NablaPackage#getNablaModule()
 * @model
 * @generated
 */
public interface NablaModule extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.cea.nabla.nabla.NablaPackage#getNablaModule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.cea.nabla.nabla.NablaModule#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Imports</b></em>' containment reference list.
   * The list contents are of type {@link fr.cea.nabla.nabla.Import}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Imports</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imports</em>' containment reference list.
   * @see fr.cea.nabla.nabla.NablaPackage#getNablaModule_Imports()
   * @model containment="true"
   * @generated
   */
  EList<Import> getImports();

  /**
   * Returns the value of the '<em><b>Blocks</b></em>' containment reference list.
   * The list contents are of type {@link fr.cea.nabla.nabla.DeclarationBlock}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Blocks</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Blocks</em>' containment reference list.
   * @see fr.cea.nabla.nabla.NablaPackage#getNablaModule_Blocks()
   * @model containment="true"
   * @generated
   */
  EList<DeclarationBlock> getBlocks();

  /**
   * Returns the value of the '<em><b>Variables</b></em>' containment reference list.
   * The list contents are of type {@link fr.cea.nabla.nabla.Instruction}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variables</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variables</em>' containment reference list.
   * @see fr.cea.nabla.nabla.NablaPackage#getNablaModule_Variables()
   * @model containment="true"
   * @generated
   */
  EList<Instruction> getVariables();

  /**
   * Returns the value of the '<em><b>Jobs</b></em>' containment reference list.
   * The list contents are of type {@link fr.cea.nabla.nabla.Job}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Jobs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Jobs</em>' containment reference list.
   * @see fr.cea.nabla.nabla.NablaPackage#getNablaModule_Jobs()
   * @model containment="true"
   * @generated
   */
  EList<Job> getJobs();

} // NablaModule
