/**
 * generated by Xtext 2.19.0
 */
package fr.cea.nabla.nabla;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Real XCompact Constant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.cea.nabla.nabla.RealXCompactConstant#getType <em>Type</em>}</li>
 *   <li>{@link fr.cea.nabla.nabla.RealXCompactConstant#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see fr.cea.nabla.nabla.NablaPackage#getRealXCompactConstant()
 * @model
 * @generated
 */
public interface RealXCompactConstant extends Expression
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link fr.cea.nabla.nabla.BasicType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see fr.cea.nabla.nabla.BasicType
   * @see #setType(BasicType)
   * @see fr.cea.nabla.nabla.NablaPackage#getRealXCompactConstant_Type()
   * @model
   * @generated
   */
  BasicType getType();

  /**
   * Sets the value of the '{@link fr.cea.nabla.nabla.RealXCompactConstant#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see fr.cea.nabla.nabla.BasicType
   * @see #getType()
   * @generated
   */
  void setType(BasicType value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(double)
   * @see fr.cea.nabla.nabla.NablaPackage#getRealXCompactConstant_Value()
   * @model
   * @generated
   */
  double getValue();

  /**
   * Sets the value of the '{@link fr.cea.nabla.nabla.RealXCompactConstant#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(double value);

} // RealXCompactConstant
