/**
 * generated by Xtext 2.19.0
 */
package fr.cea.nabla.nabla;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Space Iterator Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.cea.nabla.nabla.SpaceIteratorRef#isPrev <em>Prev</em>}</li>
 *   <li>{@link fr.cea.nabla.nabla.SpaceIteratorRef#isNext <em>Next</em>}</li>
 *   <li>{@link fr.cea.nabla.nabla.SpaceIteratorRef#getIterator <em>Iterator</em>}</li>
 * </ul>
 *
 * @see fr.cea.nabla.nabla.NablaPackage#getSpaceIteratorRef()
 * @model
 * @generated
 */
public interface SpaceIteratorRef extends IteratorRangeOrRef
{
  /**
   * Returns the value of the '<em><b>Prev</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prev</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prev</em>' attribute.
   * @see #setPrev(boolean)
   * @see fr.cea.nabla.nabla.NablaPackage#getSpaceIteratorRef_Prev()
   * @model
   * @generated
   */
  boolean isPrev();

  /**
   * Sets the value of the '{@link fr.cea.nabla.nabla.SpaceIteratorRef#isPrev <em>Prev</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prev</em>' attribute.
   * @see #isPrev()
   * @generated
   */
  void setPrev(boolean value);

  /**
   * Returns the value of the '<em><b>Next</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Next</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Next</em>' attribute.
   * @see #setNext(boolean)
   * @see fr.cea.nabla.nabla.NablaPackage#getSpaceIteratorRef_Next()
   * @model
   * @generated
   */
  boolean isNext();

  /**
   * Sets the value of the '{@link fr.cea.nabla.nabla.SpaceIteratorRef#isNext <em>Next</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Next</em>' attribute.
   * @see #isNext()
   * @generated
   */
  void setNext(boolean value);

  /**
   * Returns the value of the '<em><b>Iterator</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Iterator</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Iterator</em>' reference.
   * @see #setIterator(SpaceIterator)
   * @see fr.cea.nabla.nabla.NablaPackage#getSpaceIteratorRef_Iterator()
   * @model
   * @generated
   */
  SpaceIterator getIterator();

  /**
   * Sets the value of the '{@link fr.cea.nabla.nabla.SpaceIteratorRef#getIterator <em>Iterator</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Iterator</em>' reference.
   * @see #getIterator()
   * @generated
   */
  void setIterator(SpaceIterator value);

} // SpaceIteratorRef
