/**
 * generated by Xtext 2.19.0
 */
package fr.cea.nabla.nabla;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Space Iterator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.cea.nabla.nabla.SpaceIterator#getName <em>Name</em>}</li>
 *   <li>{@link fr.cea.nabla.nabla.SpaceIterator#getRange <em>Range</em>}</li>
 * </ul>
 *
 * @see fr.cea.nabla.nabla.NablaPackage#getSpaceIterator()
 * @model
 * @generated
 */
public interface SpaceIterator extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.cea.nabla.nabla.NablaPackage#getSpaceIterator_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.cea.nabla.nabla.SpaceIterator#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Range</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Range</em>' containment reference.
   * @see #setRange(SpaceIteratorRange)
   * @see fr.cea.nabla.nabla.NablaPackage#getSpaceIterator_Range()
   * @model containment="true"
   * @generated
   */
  SpaceIteratorRange getRange();

  /**
   * Sets the value of the '{@link fr.cea.nabla.nabla.SpaceIterator#getRange <em>Range</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Range</em>' containment reference.
   * @see #getRange()
   * @generated
   */
  void setRange(SpaceIteratorRange value);

} // SpaceIterator
