/**
 * generated by Xtext 2.19.0
 */
package fr.cea.nabla.nabla;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Space Iterator Range</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.cea.nabla.nabla.SpaceIteratorRange#getConnectivity <em>Connectivity</em>}</li>
 *   <li>{@link fr.cea.nabla.nabla.SpaceIteratorRange#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see fr.cea.nabla.nabla.NablaPackage#getSpaceIteratorRange()
 * @model
 * @generated
 */
public interface SpaceIteratorRange extends IteratorRangeOrRef
{
  /**
   * Returns the value of the '<em><b>Connectivity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Connectivity</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connectivity</em>' reference.
   * @see #setConnectivity(Connectivity)
   * @see fr.cea.nabla.nabla.NablaPackage#getSpaceIteratorRange_Connectivity()
   * @model
   * @generated
   */
  Connectivity getConnectivity();

  /**
   * Sets the value of the '{@link fr.cea.nabla.nabla.SpaceIteratorRange#getConnectivity <em>Connectivity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Connectivity</em>' reference.
   * @see #getConnectivity()
   * @generated
   */
  void setConnectivity(Connectivity value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link fr.cea.nabla.nabla.SpaceIteratorRef}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Args</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see fr.cea.nabla.nabla.NablaPackage#getSpaceIteratorRange_Args()
   * @model containment="true"
   * @generated
   */
  EList<SpaceIteratorRef> getArgs();

} // SpaceIteratorRange
