/*
 * generated by Xtext 2.19.0
 */
package fr.inria.diverse

import fr.inria.diverse.serialization.TransientValueService

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class LogoRuntimeModule extends AbstractLogoRuntimeModule {
	
	override bindITransientValueService() {
		return TransientValueService
	}
	
}
