/*
 * generated by Xtext 2.19.0
 */
package fr.inria.diverse


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LogoStandaloneSetup extends LogoStandaloneSetupGenerated {

	def static void doSetup() {
		new LogoStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
