/*
 * generated by Xtext 2.19.0
 */
package fr.cea.nabla.parser.antlr;

import com.google.inject.Inject;
import fr.cea.nabla.parser.antlr.internal.InternalNablaParser;
import fr.cea.nabla.services.NablaGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class NablaParser extends AbstractAntlrParser {

	@Inject
	private NablaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalNablaParser createParser(XtextTokenStream stream) {
		return new InternalNablaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "NablaModule";
	}

	public NablaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(NablaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
