/*
 * generated by Xtext 2.19.0
 */
package fr.inria.diverse.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLogoScopeProvider extends DelegatingScopeProvider {
}
