/*
 * generated by Xtext 2.17.0
 */
package fr.inria.diverse


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class KauluaStandaloneSetup extends KauluaStandaloneSetupGenerated {

	def static void doSetup() {
		new KauluaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
